### ISSUE TITLE
UTTB/RDTB data read issue

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/UnitTestToolbox#13]
I'm not sure if this is a UTTB or a RDTB issue, or an interaction between the two.

When we run validations for the temporalFittingEngine repository, we are having trouble reading one of the validation files.

From DB's machine, files that DB wrote are read fine, both for DB and for Geoff Aguirre (e.g., the v_tfeApplyKernal runs fine and reads its data from the archiva repository).

From Geoff Aguirre's machine, files that Geoff wrote are read fine (e.g., v_crossValidateFits runs fine from Geoff's machine and finds the remote data).  The validation data was created from Geoff's machine.  

From DB's machine, however, v_crossValidateFits thinks there is no validation data available.

When DB looks on the server directly through the web interface, it appears that the validation data is there.

So, this is a mystery.  Maybe it is some sort of permissions thing, that the data created by Geoff is not readable by others?

**Comment by benjamin-heasly** [comment]
I took a look at the server.  It looks like there may have been an artifact for crossValidateFits at some point, because I see some metadata for that artifact.  But now there is no mat-file with the actual data.

Compare to [another artifact, with a mat-file](http://52.32.77.154/repository/temporalFittingEngine/validation/full/QCM/QCMBasic/run00001/) in addition to the metadata.

I wonder how this came about.  Maybe the initial publishing of data failed?  Or maybe the artifact was deleted somehow?

So, my theory is that the artifact exists in GA's local Gradle cache, and that is why the validations run on GA's machine.  But other's can't get the data because they are not really on the server.

RDT and Gradle are usually able to detect remote updates and deletes in order to keep local caches in sync with the server.  But in this case, maybe the existence of the old metadata is confusing things.

I'm going to go ahead and try to delete the old metadata.  Then maybe you can try again from GA's and DB's machines, and see if things make sense again?

**Comment by DavidBrainard** [comment]
Rebuilding caused this problem to go away.  I'm closing.  We'll reopen if it crops up again.
